name: PoliCity
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _python_abi3_support=1.0
  - annotated-doc=0.0.4
  - annotated-types=0.6.0
  - anyio=4.10.0
  - asttokens=3.0.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2026.2.25
  - certifi=2026.2.25
  - cffi=2.0.0
  - click=8.2.1
  - comm=0.2.3
  - coverage=7.13.4
  - cpython=3.13.12
  - cryptography=46.0.5
  - debugpy=1.8.20
  - decorator=5.2.1
  - email-validator=2.3.0
  - executing=2.2.1
  - fastapi-cli=0.0.20
  - h11=0.16.0
  - httpcore=1.0.9
  - httptools=0.7.1
  - httpx=0.28.1
  - icu=73.1
  - idna=3.11
  - iniconfig=2.3.0
  - intel-openmp=2025.0.0
  - ipykernel=7.2.0
  - ipython=9.10.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.3
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libedit=3.1.20250104
  - libexpat=2.7.4
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libmpdec=4.0.0
  - libsodium=1.0.20
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libuv=1.48.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - markdown-it-py=4.0.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.2.1
  - mdurl=0.1.2
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=2.4.2
  - numpy-base=2.4.2
  - openssl=3.6.1
  - packaging=25.0
  - pandas=3.0.0
  - parso=0.8.6
  - pexpect=4.9.0
  - pip=26.0.1
  - platformdirs=4.9.2
  - pluggy=1.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.2.2
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.23
  - pydantic-core=2.41.5
  - pydantic-extra-types=2.11.0
  - pydantic-settings=2.12.0
  - pygments=2.19.2
  - pytest=9.0.2
  - pytest-asyncio=1.3.0
  - pytest-cov=7.0.0
  - python=3.13.12
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.2.1
  - python-gil=3.13.12
  - python-jose=3.5.0
  - python-multipart=0.0.22
  - python_abi=3.13
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - readline=8.3
  - rich=14.2.0
  - rich-toolkit=0.17.1
  - scikit-learn=1.8.0
  - scipy=1.17.0
  - setuptools=80.10.2
  - shellingham=1.5.4
  - six=1.17.0
  - sniffio=1.3.1
  - sqlite=3.51.1
  - stack_data=0.6.3
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - threadpoolctl=3.5.0
  - tk=8.6.15
  - toml=0.10.2
  - tornado=6.5.4
  - traitlets=5.14.3
  - typer=0.20.0
  - typer-slim=0.20.0
  - typer-slim-standard=0.20.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025c
  - uvicorn-standard=0.40.0
  - uvloop=0.22.1
  - watchfiles=1.1.1
  - wcwidth=0.6.0
  - websockets=15.0.1
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.3.1
  - pip:
      - ada-url==1.30.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - attrs==25.4.0
      - auth0-api-python==1.0.0b6
      - auth0-fastapi==1.0.0b6
      - auth0-fastapi-api==1.0.0b5
      - auth0-python==5.1.0
      - auth0-server-python==1.0.0b8
      - authlib==1.6.8
      - charset-normalizer==3.4.4
      - dnspython==1.16.0
      - fastapi==0.115.14
      - frozenlist==1.8.0
      - itsdangerous==2.2.0
      - jwcrypto==1.5.6
      - motor==3.7.1
      - multidict==6.7.1
      - propcache==0.4.1
      - pydantic==2.12.5
      - pyjwt==2.11.0
      - pymongo==3.12.0
      - requests==2.32.5
      - starlette==0.46.2
      - urllib3==2.6.3
      - uvicorn==0.34.3
      - yarl==1.22.0
prefix: /home/pradhan/miniconda3/envs/PoliCity
